name: cvae
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.14
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - pytorch-lightning=2.2.2
  - pyyaml=6.0.1
  - torchvision=0.17.2
  - torchmetrics=1.3.2
  - tqdm=4.66.2
  - numpy=1.26.4
  - scipy=1.12.0
  - pip:
    - timm==0.9.16
    - medmnist==3.0.1
    - medimeta